### PR TITLE
Allow astc-encoder to be built as a static library

### PR DESCRIPTION
**Pull request by Themaister**
Currently the CMake build does not support building the API as a static library.

I'm not sure what the right approach is here. I had to hack together static library support for Granite integration.

### CODE REVIEW

**Comment by solidpixel** [comment]
Happy to take a look - ability to build as a static/dynamic library has been on my "todo" for a while.  Only caveat here is that the core codec interface isn't pure C (we use references) so it's only going to reliably work on the same toolset, etc (due to name mangling differences across compilers).

**Comment by Themaister** [comment]
Static lib is fine for that, especially in CMake, since I do `target_link_libraries(engine PRIVATE astc-encoder)`.

**Comment by solidpixel** [comment]
> On that note, is there any reason why an API that looks very much like C is actually a C++-only API?

Not really - given the core code is C++ I just defaulted to writing the API in C++.

**Comment by solidpixel** [comment]
Merged the static library changes to `main` - tested locally on Linux and Windows, and will let the macOS build run overnight to check.

**Pull request closed without merging**
