### PR TITLE
Tidy flags code sequence

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by solidpixel** [comment]
Sorry, I'm not willing to accept this one. 

Flags don't need to be tidy - users should be using the symbolic values, and the actual number is only ever read by the machine. 

Changing this causes a binary ABI break so any user code will break if they fail to update the header, and will get fun bugs even if they recompile if their source code happens to be using the numeric values rather than the symbolic ones.

Binary ABI stability is more important than a cosmetic change here.

**Comment by halx99** [comment]
ok, maybe move follow const to last is better
```cpp
static const unsigned int ASTCENC_FLG_MAP_RGBM             = 1 << 6;
```

Because when I try to add a new flags, I forget read all flags, and simply add a new flags same with `ASTCENC_FLG_MAP_RGBM             ` bug me some times.

**Comment by solidpixel** [comment]
Yeah, reordering them in the header would be OK, just don't change the values. Note there can be holes in the values where old flags have been retired.

**Comment by halx99** [comment]
Done by new one: #327

**Pull request closed without merging**
