### PR TITLE
Added -flip to support OpenGL

### PR DESCRIPTION
**Pull request by Micha0**
As I was having the same issue as #26, I decided to fix it. Hopefully this inspires you to have this feature. For me the "DirectX argument" doesn't really fly as most desktop hardware doesn't support the ASTC format while a lot of new mobile phones do, where OpenGL is very popular. Since Vulkan and Metal do have the same texture coordinate system as DirectX, the default is kept unflipped.

### CODE REVIEW

**Comment by solidpixel** [comment]
Happy for this to be merged to master; also tagged for 2.0 so we remember to pull this change across to the 2.0 branch.

**Comment by Micha0** [comment]
Sounds fair @solidpixel, thank you. As this is now a feature request for 2.0, I guess you don't need documentation bit? (I'm not sure how much the 2.0 codebase is different from 1.x)

**Comment by solidpixel** [comment]
No, thats fine - I can add the documentation when we do the 2.0 flavored version of this. I'll reject this PR - but I've raised an issue to track this for for the 2.0 branch - see  #82. Will try to get around to this soon, so you're not waiting for it for a long time (although beware the current 2.0 branch is very much an early alpha).

**Comment by solidpixel** [comment]
FYI, `-yflip` now on master.

**Pull request closed without merging**
